# ===================================
# CONFIGURACION DE PRODUCCION
# ===================================

# PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/quincho
spring.datasource.username=postgres
spring.datasource.password=123456
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA/Hibernate
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Logging
logging.level.root=WARN
logging.level.com.elumbral.quincho=INFO

# Email
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=cuentamagis482@gmail.com
spring.mail.password=fvhhwaataavxtxtf
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# CORS
cors.allowed.origins=${CORS_ALLOWED_ORIGINS}

# Archivos
spring.servlet.multipart.max-file-size=10MB
